apiVersion: v1
kind: Service
metadata:
  name: {{ include "search-service.fullname" . }}
  labels:
    {{- include "search-service.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Name={{ .Values.service.annotations.albTags }}-elb,Project=Headhuntr.IO,BillingCode={{ .Values.service.annotations.albTags }}-infra,Environment={{ .Values.service.annotations.albTags }},Owner=terraform"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "search-service.selectorLabels" . | nindent 4 }}
