openapi: "3.0.1"
info:
  title: "HHV2 API"
  description: "Platform for the Headhuntr.IO Secret Mobile App"
  version: "2020-11-03 10:39:29UTC"
servers:
  - url: "https://v798xp0ld7.execute-api.us-east-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: ""
tags:
  - name: "Project"
    x-amazon-apigateway-tag-value: "HeadhuntrV2"
  - name: "Environment"
    x-amazon-apigateway-tag-value: "hhv2"
  - name: "Owner"
    x-amazon-apigateway-tag-value: "terraformV2"
  - name: "BillingCode"
    x-amazon-apigateway-tag-value: "hhv2-infra-2020-10-17"

paths:
  /health/actuator:
    get:
      description: Shows the health status of the server
      summary: Health Check
      operationId: "GET Resource"
      responses:
        default:
          description: "Default response for GET /{proxy+}"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        connectionId: "9763tu"
        type: "http_proxy"
        httpMethod: "ANY"
        uri: "arn:aws:elasticloadbalancing:us-east-1:327229172692:listener/net/ae22663f181ac4cfba685c29f09574e7/8aaa50035cab3a19/f74277f17d8e35b0"
        connectionType: "VPC_LINK"
        timeoutInMillis: 29000

components:
  schemas:
    HealthCheck:
      type: object


x-amazon-apigateway-cors:
  allowMethods:
    - "*"
  allowHeaders:
    - "*"
  maxAge: 300
  allowCredentials: true
x-amazon-apigateway-importexport-version: "1.0"
